import Head from 'next/head';
import Link from 'next/link';

const features = [
  { icon: '💬', title: 'WhatsApp Automation', desc: 'Auto-reply to leads instantly. Welcome messages, follow-ups, and alerts sent to your number the moment a lead comes in.' },
  { icon: '📧', title: 'Email Campaigns', desc: 'Welcome series, festival campaigns, re-engagement — all automated. Set it once, runs forever.' },
  { icon: '📸', title: 'Instagram DM Bot', desc: 'AI-powered auto-replies to Instagram DMs using Gemini. Handles pricing, availability, and custom enquiries 24/7.' },
  { icon: '📊', title: 'Lead CRM', desc: 'Every lead captured in Google Sheets automatically. Track status, source, and conversion rate in real time.' },
  { icon: '✈️', title: 'Telegram Alerts (Free)', desc: 'Get instant Telegram notifications every time a new lead comes in. Broadcast campaigns to your channel — completely free.' },
  { icon: '🔴', title: 'Reddit Reach (Free)', desc: 'Auto-post to targeted subreddits to drive organic traffic. Reach thousands of potential customers at zero cost.' },
  { icon: '🤖', title: 'Gemini AI', desc: 'Smart, brand-aware responses generated by Google Gemini AI. Sounds human, works at scale.' },
  { icon: '📈', title: 'Analytics Dashboard', desc: 'See total leads, conversion rate, WhatsApp usage, and campaign performance in one place.' },
];

const plans = [
  {
    name: 'Starter',
    price: '₹2,000',
    period: '/month',
    color: '#6366f1',
    features: ['WhatsApp automation', 'Email campaigns', '1,000 messages/month', 'Telegram notifications (free)', 'Lead CRM (Google Sheets)', 'Analytics dashboard'],
    cta: 'Get Started Free',
    popular: false,
  },
  {
    name: 'Growth',
    price: '₹5,000',
    period: '/month',
    color: '#8b5cf6',
    features: ['Everything in Starter', 'Instagram DM bot', 'Reddit organic reach (free)', 'Festival campaigns', 'Re-engagement sequences', 'Priority support'],
    cta: 'Start Growth Plan',
    popular: true,
  },
  {
    name: 'Scale',
    price: '₹10,000',
    period: '/month',
    color: '#06b6d4',
    features: ['Everything in Growth', 'Custom message limit', 'Multiple team members', 'Dedicated onboarding', 'Monthly strategy call'],
    cta: 'Contact Us',
    popular: false,
  },
];

const stats = [
  { value: '1,000+', label: 'Messages automated/month' },
  { value: '3x',     label: 'Faster lead response' },
  { value: '80%',    label: 'Reduction in manual work' },
  { value: '24/7',   label: 'Always-on automation' },
];

export default function LandingPage() {
  return (
    <>
      <Head>
        <title>AutoMarket — WhatsApp & Email Marketing Automation for Indian Businesses</title>
        <meta name="description" content="Automate your WhatsApp messages, email campaigns, and Instagram DMs. Built for Indian businesses. Start free." />
      </Head>

      <div style={s.page}>
        {/* NAV */}
        <nav style={s.nav}>
          <div style={s.navInner}>
            <span style={s.logo}>⚡ AutoMarket</span>
            <div style={s.navLinks}>
              <a href="#features" style={s.navLink}>Features</a>
              <a href="#pricing" style={s.navLink}>Pricing</a>
              <Link href="/auth/login" style={s.navLink}>Login</Link>
              <Link href="/auth/signup" style={s.navBtn}>Get Started Free →</Link>
            </div>
          </div>
        </nav>

        {/* HERO */}
        <section style={s.hero}>
          <div style={s.heroInner}>
            <div style={s.badge}>🇮🇳 Built for Indian Businesses</div>
            <h1 style={s.heroTitle}>
              Automate Your Marketing.<br />
              <span style={s.heroGradient}>Generate Leads While You Sleep.</span>
            </h1>
            <p style={s.heroSub}>
              WhatsApp automation, email campaigns, and Instagram DM bot — all in one platform.
              Set it up once, run forever. No tech skills needed.
            </p>
            <div style={s.heroBtns}>
              <Link href="/auth/signup" style={s.btnPrimary}>Start Free Today →</Link>
              <a href="#features" style={s.btnSecondary}>See How It Works</a>
            </div>
            <p style={s.heroNote}>✅ Free to start &nbsp;·&nbsp; ✅ No credit card &nbsp;·&nbsp; ✅ Setup in 10 minutes</p>
          </div>
        </section>

        {/* STATS */}
        <section style={s.statsBar}>
          {stats.map((stat, i) => (
            <div key={i} style={s.statItem}>
              <div style={s.statValue}>{stat.value}</div>
              <div style={s.statLabel}>{stat.label}</div>
            </div>
          ))}
        </section>

        {/* FEATURES */}
        <section id="features" style={s.section}>
          <div style={s.sectionInner}>
            <div style={s.sectionBadge}>Features</div>
            <h2 style={s.sectionTitle}>Everything you need to automate your marketing</h2>
            <p style={s.sectionSub}>One platform. WhatsApp, Email, Instagram. All automated.</p>

            <div style={s.featGrid}>
              {features.map((f, i) => (
                <div key={i} style={s.featCard}>
                  <div style={s.featIcon}>{f.icon}</div>
                  <h3 style={s.featTitle}>{f.title}</h3>
                  <p style={s.featDesc}>{f.desc}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* HOW IT WORKS */}
        <section style={{ ...s.section, background: '#f8f9ff' }}>
          <div style={s.sectionInner}>
            <div style={s.sectionBadge}>How It Works</div>
            <h2 style={s.sectionTitle}>Up and running in 4 steps</h2>

            <div style={s.stepsGrid}>
              {[
                { n: '1', title: 'Sign Up Free', desc: 'Create your account in 30 seconds. No credit card required.' },
                { n: '2', title: 'Connect Your Tools', desc: 'Add your WhatsApp (AiSensy), Gmail, and Google Sheets. Takes 10 minutes.' },
                { n: '3', title: 'Set Your Brand', desc: 'Enter your business name, offers, and website. The AI does the rest.' },
                { n: '4', title: 'Go Live', desc: 'Share your webhook URL and watch leads get automated messages instantly.' },
              ].map((step, i) => (
                <div key={i} style={s.stepCard}>
                  <div style={s.stepNum}>{step.n}</div>
                  <h3 style={s.stepTitle}>{step.title}</h3>
                  <p style={s.stepDesc}>{step.desc}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* PRICING */}
        <section id="pricing" style={s.section}>
          <div style={s.sectionInner}>
            <div style={s.sectionBadge}>Pricing</div>
            <h2 style={s.sectionTitle}>Simple, transparent pricing</h2>
            <p style={s.sectionSub}>Start free. Upgrade as you grow.</p>

            <div style={s.pricingGrid}>
              {plans.map((plan, i) => (
                <div key={i} style={{ ...s.pricingCard, ...(plan.popular ? s.pricingCardPopular : {}) }}>
                  {plan.popular && <div style={s.popularBadge}>Most Popular</div>}
                  <h3 style={s.planName}>{plan.name}</h3>
                  <div style={s.planPrice}>
                    <span style={{ ...s.planAmount, color: plan.color }}>{plan.price}</span>
                    <span style={s.planPeriod}>{plan.period}</span>
                  </div>
                  <ul style={s.planFeatures}>
                    {plan.features.map((f, j) => (
                      <li key={j} style={s.planFeature}>✓ {f}</li>
                    ))}
                  </ul>
                  <Link href="/auth/signup" style={{ ...s.planBtn, background: plan.color }}>
                    {plan.cta}
                  </Link>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* CTA */}
        <section style={s.ctaSection}>
          <div style={s.ctaInner}>
            <h2 style={s.ctaTitle}>Ready to automate your marketing?</h2>
            <p style={s.ctaSub}>Join businesses already saving 80% of their marketing time.</p>
            <Link href="/auth/signup" style={s.btnPrimary}>Get Started Free →</Link>
          </div>
        </section>

        {/* FOOTER */}
        <footer style={s.footer}>
          <div style={s.footerInner}>
            <span style={s.logo}>⚡ AutoMarket</span>
            <p style={s.footerText}>WhatsApp · Email · Instagram automation for Indian businesses.</p>
            <div style={s.footerLinks}>
              <Link href="/auth/login" style={s.footerLink}>Login</Link>
              <Link href="/auth/signup" style={s.footerLink}>Sign Up</Link>
            </div>
          </div>
        </footer>
      </div>
    </>
  );
}

export async function getServerSideProps() {
  return { props: {} };
}

const s = {
  page:       { fontFamily: "'Inter', Arial, sans-serif", color: '#1a1a1a', background: '#fff' },

  // NAV
  nav:        { position: 'sticky', top: 0, background: 'rgba(255,255,255,0.95)', backdropFilter: 'blur(8px)', borderBottom: '1px solid #f0f0f0', zIndex: 100 },
  navInner:   { maxWidth: '1100px', margin: '0 auto', padding: '0 24px', height: '64px', display: 'flex', alignItems: 'center', justifyContent: 'space-between' },
  logo:       { fontSize: '20px', fontWeight: 800, color: '#6366f1' },
  navLinks:   { display: 'flex', alignItems: 'center', gap: '28px' },
  navLink:    { fontSize: '14px', color: '#555', textDecoration: 'none', fontWeight: 500 },
  navBtn:     { fontSize: '14px', background: '#6366f1', color: '#fff', padding: '8px 18px', borderRadius: '8px', textDecoration: 'none', fontWeight: 600 },

  // HERO
  hero:       { background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)', padding: '100px 24px 80px', textAlign: 'center' },
  heroInner:  { maxWidth: '800px', margin: '0 auto' },
  badge:      { display: 'inline-block', background: 'rgba(255,255,255,0.2)', color: '#fff', padding: '6px 16px', borderRadius: '999px', fontSize: '13px', fontWeight: 600, marginBottom: '24px' },
  heroTitle:  { fontSize: 'clamp(32px, 5vw, 56px)', fontWeight: 800, color: '#fff', lineHeight: 1.15, margin: '0 0 20px' },
  heroGradient: { color: '#fcd34d' },
  heroSub:    { fontSize: '18px', color: 'rgba(255,255,255,0.85)', lineHeight: 1.6, margin: '0 0 36px' },
  heroBtns:   { display: 'flex', gap: '16px', justifyContent: 'center', flexWrap: 'wrap', marginBottom: '20px' },
  heroNote:   { fontSize: '13px', color: 'rgba(255,255,255,0.7)' },

  // BUTTONS
  btnPrimary:   { background: '#fcd34d', color: '#1a1a1a', padding: '14px 32px', borderRadius: '10px', fontWeight: 700, fontSize: '16px', textDecoration: 'none', display: 'inline-block' },
  btnSecondary: { background: 'rgba(255,255,255,0.15)', color: '#fff', padding: '14px 32px', borderRadius: '10px', fontWeight: 600, fontSize: '16px', textDecoration: 'none', display: 'inline-block', border: '1px solid rgba(255,255,255,0.3)' },

  // STATS
  statsBar:   { background: '#1a1a1a', padding: '40px 24px', display: 'flex', justifyContent: 'center', gap: '60px', flexWrap: 'wrap' },
  statItem:   { textAlign: 'center' },
  statValue:  { fontSize: '36px', fontWeight: 800, color: '#fcd34d' },
  statLabel:  { fontSize: '13px', color: '#aaa', marginTop: '4px' },

  // SECTIONS
  section:    { padding: '80px 24px' },
  sectionInner: { maxWidth: '1100px', margin: '0 auto' },
  sectionBadge: { display: 'inline-block', background: '#eef2ff', color: '#6366f1', padding: '5px 14px', borderRadius: '999px', fontSize: '12px', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.5px', marginBottom: '16px' },
  sectionTitle: { fontSize: 'clamp(26px, 4vw, 40px)', fontWeight: 800, margin: '0 0 12px', lineHeight: 1.2 },
  sectionSub:   { fontSize: '17px', color: '#666', margin: '0 0 48px' },

  // FEATURES
  featGrid:   { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))', gap: '24px' },
  featCard:   { background: '#f8f9ff', borderRadius: '16px', padding: '28px', border: '1px solid #e8eaff' },
  featIcon:   { fontSize: '36px', marginBottom: '16px' },
  featTitle:  { fontSize: '18px', fontWeight: 700, margin: '0 0 8px' },
  featDesc:   { fontSize: '14px', color: '#666', lineHeight: 1.6, margin: 0 },

  // STEPS
  stepsGrid:  { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))', gap: '24px' },
  stepCard:   { textAlign: 'center', padding: '32px 20px' },
  stepNum:    { width: '48px', height: '48px', background: '#6366f1', color: '#fff', borderRadius: '50%', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '20px', fontWeight: 800, margin: '0 auto 16px' },
  stepTitle:  { fontSize: '18px', fontWeight: 700, margin: '0 0 8px' },
  stepDesc:   { fontSize: '14px', color: '#666', lineHeight: 1.6, margin: 0 },

  // PRICING
  pricingGrid:       { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: '24px', alignItems: 'start' },
  pricingCard:       { border: '1px solid #e5e7eb', borderRadius: '16px', padding: '32px', position: 'relative' },
  pricingCardPopular:{ border: '2px solid #6366f1', boxShadow: '0 8px 32px rgba(99,102,241,0.15)' },
  popularBadge:      { position: 'absolute', top: '-13px', left: '50%', transform: 'translateX(-50%)', background: '#6366f1', color: '#fff', padding: '4px 16px', borderRadius: '999px', fontSize: '12px', fontWeight: 700 },
  planName:          { fontSize: '20px', fontWeight: 700, margin: '0 0 12px' },
  planPrice:         { display: 'flex', alignItems: 'baseline', gap: '4px', margin: '0 0 24px' },
  planAmount:        { fontSize: '40px', fontWeight: 800 },
  planPeriod:        { fontSize: '14px', color: '#888' },
  planFeatures:      { listStyle: 'none', padding: 0, margin: '0 0 28px' },
  planFeature:       { fontSize: '14px', color: '#555', padding: '6px 0', borderBottom: '1px solid #f0f0f0' },
  planBtn:           { display: 'block', textAlign: 'center', color: '#fff', padding: '12px', borderRadius: '10px', fontWeight: 700, fontSize: '15px', textDecoration: 'none' },

  // CTA
  ctaSection: { background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)', padding: '80px 24px', textAlign: 'center' },
  ctaInner:   { maxWidth: '600px', margin: '0 auto' },
  ctaTitle:   { fontSize: 'clamp(26px, 4vw, 40px)', fontWeight: 800, color: '#fff', margin: '0 0 12px' },
  ctaSub:     { fontSize: '17px', color: 'rgba(255,255,255,0.8)', margin: '0 0 32px' },

  // FOOTER
  footer:      { background: '#1a1a1a', padding: '40px 24px' },
  footerInner: { maxWidth: '1100px', margin: '0 auto', textAlign: 'center' },
  footerText:  { fontSize: '13px', color: '#888', margin: '8px 0 16px' },
  footerLinks: { display: 'flex', justifyContent: 'center', gap: '24px' },
  footerLink:  { fontSize: '13px', color: '#aaa', textDecoration: 'none' },
};
